/// Flutter icons OsolIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OsolIcon
///      fonts:
///       - asset: fonts/OsolIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class OsolIcon {
  OsolIcon._();

  static const _kFontFam = 'OsolIcon';
  static const String? _kFontPkg = null;

  static const IconData estate = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compund = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_3 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData label = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData images = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData category = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square_ = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData label2 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viewstream = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menutogle = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_1 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mapicon = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData customer = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacy = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData examilation = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
